Repository Homebrew/homebrew-cask-versions, pull requests merged in 2020-12, with the labels that each got.

#10018 CONTRIBUTING.md: style updates
  CONTRIBUTING.md
Labels: documentation

#10019 README.md: updates for deprecated commands
  README.md
Labels: documentation

#10037 Update android-studio-preview-canary from 2020.3.1.1,202.6983675 to 2020.3.1.2,202.7006259
  Casks/android-studio-preview-canary.rb
Labels: ci-syntax-only

#10052 Update verified parameter – group 4
  Casks/pdf-expert-beta.rb
  Casks/pgadmin3.rb
  Casks/postgres-beta.rb
  Casks/rstudio-preview.rb
  Casks/scribus-dev.rb
  Casks/skype-preview.rb
  Casks/slack-beta.rb
  Casks/sourcetree-beta.rb
  Casks/sublime-merge-dev.rb
  Casks/telegram-desktop-dev.rb
Labels: ci-syntax-only

#10051 Update verified parameter – group 3
  Casks/lando-edge.rb
  Casks/libreoffice-still.rb
  Casks/microsoft-edge-beta.rb
  Casks/microsoft-edge-dev.rb
  Casks/microsoft-office-2016.rb
  Casks/miniconda2.rb
  Casks/morpheus-beta.rb
  Casks/mullvadvpn-beta.rb
  Casks/openemu-experimental.rb
  Casks/papers3.rb
Labels: ci-syntax-only

#10056 Update signal-beta from 1.39.2-beta.1 to 1.39.2-beta.2
  Casks/signal-beta.rb
Labels: ci-skip-appcast

#10050 Update verified parameter – group 2
  Casks/github-beta.rb
  Casks/google-japanese-ime-dev.rb
  Casks/hex-fiend-beta.rb
  Casks/hyper-canary.rb
  Casks/java6.rb
  Casks/kap-beta.rb
  Casks/keepassxc-beta.rb
  Casks/keka-beta.rb
  Casks/keyboard-maestro8.rb
  Casks/kitematic0176.rb
Labels: ci-syntax-only

#10054 Update verified parameter – group 6
  Casks/wine-staging.rb
Labels: ci-skip-appcast

#10055 wine-devel: remove conflicts_with formula
  Casks/wine-devel.rb
Labels: ci-skip-appcast

#10057 Update telegram-desktop-dev from 2.4.9.beta to 2.4.12.beta
  Casks/telegram-desktop-dev.rb
Labels: ci-skip-appcast

#10061 Update microsoft-edge-dev from 88.0.705.15 to 89.0.723.0
  Casks/microsoft-edge-dev.rb
Labels: ci-skip-appcast

#10065 Use `sha256 :no_check` for unversioned URLs
  Casks/affinity-designer-beta.rb
  Casks/affinity-photo-beta.rb
  Casks/termius-beta.rb
Labels: ci-syntax-only

#10049 Update verified parameter – group 1
  Casks/chromedriver-beta.rb
  Casks/cleanmymac3.rb
  Casks/darktable-dev.rb
  Casks/deadbeef-devel.rb
  Casks/discord-canary.rb
  Casks/dropbox-beta.rb
  Casks/ferdi-beta.rb
  Casks/firefox-esr.rb
  Casks/firefox-nightly.rb
  Casks/freecad-pre.rb
Labels: ci-syntax-only

#10048 Update verified parameter – group 0
  Casks/adoptopenjdk8.rb
  Casks/affinity-designer-beta.rb
  Casks/affinity-photo-beta.rb
  Casks/affinity-publisher-beta.rb
  Casks/anaconda2.rb
  Casks/android-studio-preview-beta.rb
  Casks/atom-beta.rb
  Casks/brave-browser-beta.rb
  Casks/brave-browser-dev.rb
  Casks/brave-browser-nightly.rb
Labels: ci-syntax-only

#10053 Update verified parameter – group 5
  Casks/textmate-preview.rb
  Casks/thunderbird-beta.rb
  Casks/thunderbird-daily.rb
  Casks/tla-plus-toolbox-nightly.rb
  Casks/tower2.rb
  Casks/tunnelblick-beta.rb
  Casks/visual-studio-code-insiders.rb
  Casks/vmware-fusion-tech-preview.rb
  Casks/vox2.rb
  Casks/whoozle-android-file-transfer-nightly.rb
Labels: ci-syntax-only

#10089 Remove “required as upstream package is updated in-place” comment
  Casks/firefox-nightly.rb
  Casks/julia-nightly.rb
  Casks/thunderbird-daily.rb
Labels: ci-syntax-only

#10110 Update background-music-pre from 0.4.0-SNAPSHOT-c024116 to 0.4.0-SNAPSHOT-c0ab98b
  Casks/background-music-pre.rb
Labels: ci-syntax-only

#10149 Update android-studio-preview-beta from 4.1.0.11,201.6565218 to 4.2.0.18,202.7008469
  Casks/android-studio-preview-beta.rb
Labels: ci-syntax-only

#10150 Update android-studio-preview-canary from 2020.3.1.2,202.7006259 to 2020.3.1.3
  Casks/android-studio-preview-canary.rb
Labels: ci-syntax-only
